package com.mangaku.local

// Generated from the pinned Keiyoushi build manifests. See vendor/keiyoushi/inventory.json.
internal val arabicSources = listOf(
    Source("anyonemanga", "Anyone Manga", "madara", listOf("https://anyonemanga.com"), false),
    Source("arabhentai", "هنتاي العرب - نت", "", listOf("https://arabhentai.net"), true),
    Source("arabmanhwa", "ArabManhwa", "madara", listOf("https://arabmanhwa.com"), true),
    Source("arabshentai", "هنتاي العرب", "", listOf("https://arabshentai.com"), true),
    Source("arabtoons", "عرب تونز", "madara", listOf("https://arabtoons.net"), true),
    Source("arbxcomix", "ArbxComix", "madara", listOf("https://arbxcomix.com"), true),
    Source("areamanga", "أريا مانجا", "mangathemesia", listOf("https://ar.kenmanga.com"), false),
    Source("ariatoon", "AriaToon", "", listOf("https://ariatoon.com"), false),
    Source("azora", "Azora", "iken", listOf("https://azorafly.com"), false),
    Source("comicverse", "Comic Verse", "zeistmanga", listOf("https://arcomixverse.blogspot.com"), false),
    Source("despairmanga", "Despair Manga", "mangathemesia", listOf("https://despair-manga.net"), false),
    Source("detectiveconanar", "شبكة كونان العربية", "madara", listOf("https://manga.detectiveconanar.com"), false),
    Source("dilar", "Dilar", "", listOf("https://dilar.tube"), false),
    Source("duskoryvile", "Duskoryvile", "", listOf("https://duskoryvile.com"), true),
    Source("empirewebtoon", "Empire Webtoon", "madara", listOf("https://webtoonempire-bl.com"), true),
    Source("eshadow", "EShadow", "", listOf("https://eshadow.net"), false),
    Source("goonscans", "Goon Scans", "mangathemesia", listOf("https://goonscans.org"), true),
    Source("hentailek", "هنتاي ليك", "", listOf("https://hentailek.com"), true),
    Source("hentaiman", "HentaiMan", "", listOf("https://hentaiman.net"), true),
    Source("hentaislayer", "هنتاي سلاير", "fuzzydoodle", listOf("https://hentaislayer.net"), true),
    Source("hijala", "Hijala", "mangathemesia", listOf("https://hijala.com"), false),
    Source("hizomanga", "Hizo Manga", "madara", listOf("https://hizomanga.net"), false),
    Source("kawiimanga", "Kawii Manga", "", listOf("https://kawaiimanga.org"), false),
    Source("lavascans", "Lava Scans", "mangathemesia", listOf("https://lavascans.com"), false),
    Source("lonertranslations", "Loner Translations", "zeistmanga", listOf("https://loner-tl.blogspot.com"), false),
    Source("manga3asq", "مانجا العاشق", "madara", listOf("https://3asq.online"), false),
    Source("mangaailand", "Manga Ai Land", "zeistmanga", listOf("https://manga-ai-land.blogspot.com"), false),
    Source("mangacloud", "MangaCloud", "", listOf("https://mangacloud.online"), false),
    Source("mangadar", "MangaDar", "", listOf("https://mangadar.com"), false),
    Source("mangahub", "MangaHub", "zeistmanga", listOf("https://www.mangaxhentai.com"), true),
    Source("mangalek", "مانجا ليك", "madaralegacy", listOf("https://mangalik.net", "https://lekmanga.online", "https://like-manga.net", "https://lekmanga.site", "https://manga-leko.site"), false),
    Source("mangalink", "مانجا لينك", "madara", listOf("https://link-manga.net"), false),
    Source("mangalionz", "MangaLionz", "madaralegacy", listOf("https://manga-lionz.org"), false),
    Source("mangaspark", "MangaSpark", "madaralegacy", listOf("https://sparkmanga.net"), false),
    Source("mangastarz", "Manga Starz", "madara", listOf("https://starzmanga.com"), false),
    Source("mangaswat", "MangaSwat", "", listOf("https://meshmanga.com"), false),
    Source("mangatales", "Manga Tales", "", listOf("https://www.mangatales.com"), false),
    Source("mangatek", "MangaTek", "", listOf("https://mangatek.com"), false),
    Source("mangatime", "MangaTime", "", listOf("https://mangatime.org"), false),
    Source("mangatuk", "MangaTuk", "madaralegacy", listOf("https://mangatuk.com"), false),
    Source("manhatic", "Manhatic", "madara", listOf("https://manhatic.com"), true),
    Source("manhatok", "Manhatok", "zeistmanga", listOf("https://manhatok.blogspot.com"), false),
    Source("murim", "Murim", "zeistmanga", listOf("https://www.murim.site"), false),
    Source("neverscans", "NeverScans", "", listOf("https://neverscans.com"), false),
    Source("oduto", "Oduto", "", listOf("https://nb19u.blogspot.com"), false),
    Source("onma", "مانجا اون لاين", "mmrcms", listOf("https://onma.me"), false),
    Source("orcamanga", "Orca Manga", "zeistmanga", listOf("https://infinity896.blogspot.com"), false),
    Source("paradisebl", "Paradise BL", "madara", listOf("https://paradise-bl.com"), true),
    Source("rocksmanga", "Rocks Manga", "madaralegacy", listOf("https://rocksmanga.com"), false),
    Source("stellarsaber", "StellarSaber", "", listOf("https://stellarsaber.pro"), false),
    Source("teamx", "Team X", "", listOf("https://olympustaff.com"), false),
    Source("xsanomanga", "XSano Manga", "zeistmanga", listOf("https://www.xsano-manga.com"), false),
    Source("yokai", "Yokai", "zeistmanga", listOf("https://yokai-team.blogspot.com"), false),
    Source("yonabar", "Yona Bar", "madaralegacy", listOf("https://yonaber.com"), true),
    Source("yurimoonsub", "Yuri Moon Sub", "zeistmanga", listOf("https://yurimoonsub.blogspot.com"), true),
)
